name: Build

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Upgrade Gradle Wrapper to 7.6.4
        run: ./gradlew wrapper --gradle-version 7.6.4 --distribution-type all
        working-directory: telon-gateway-app/android

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache NPM Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install
        working-directory: telon-gateway-app

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses || true

      - name: Bundle React Native App
        run: |
          mkdir -p android/app/build/intermediates/assets/release/
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/build/intermediates/assets/release/index.android.bundle \
            --assets-dest android/app/build/intermediates/res/merged/release
        working-directory: telon-gateway-app

      - name: Build Android App Bundle
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew bundleRelease -Pkeystore.password=${{ secrets.KEYSTORE_PASSWORD }}
        working-directory: telon-gateway-app

      - name: Upload Android App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: android-bundle
          path: telon-gateway-app/android/app/build/outputs/bundle/release/app-release.aab
