name: Build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

#      - name: Setup Node.js
#        uses: actions/setup-node@v2
#        with:
#          #node-version: 20.18.1
#          node-version: 12

#      - name: Install dependencies
#        run: npm install
#        working-directory: telon-gateway-app
#
#      - name: Run tests
#        run: npm test

  build_android:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      #- name: Setup Java 8
      #  uses: actions/setup-java@v2
      #  with:
      #    distribution: 'temurin'
      #    java-version: '8' # Требуется Java 8 для Gradle
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      #- name: Setup Java 17
      #  uses: actions/setup-java@v2
      #  with:
      #    distribution: 'temurin'
      #    java-version: '17'

      #- name: Setup Node.js
      #  uses: actions/setup-node@v2
      #  with:
      #    node-version: 12
      #    #node-version: 18.19.0

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 29
          ndk: true      

      - name: Navigate to Project Root
        run: cd $GITHUB_WORKSPACE
        working-directory: telon-gateway-app

      - name: Install Dependencies
        run: npm install
        working-directory: telon-gateway-app

      #- name: Install NDK (if required)
      #  run: |
      #    sdkmanager "ndk;21.4.7075529"
      #    echo "ndk.dir=/usr/local/lib/android/sdk/ndk/21.4.7075529" >> android/local.properties
      #  working-directory: telon-gateway-app        
      #  env:
      #    ANDROID_HOME: ${{ runner.tool_cache }}/android-sdk
      #    PATH: $PATH:${{ runner.tool_cache }}/android-sdk/cmdline-tools/latest/bin

      - name: Build Android App Bundle
        run: |
          mkdir -p android/app/build/intermediates/assets/release/
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/build/intermediates/assets/release/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/release
        working-directory: telon-gateway-app

      - name: Build Android Release
        run: |
          cd android
          chmod +x gradlew 
          ./gradlew clean
          ./gradlew wrapper --gradle-version 6.2.2 --distribution-type all
          ./gradlew bundleRelease -Pkeystore.password=${{ secrets.KEYSTORE_PASSWORD }}
        working-directory: telon-gateway-app

  download_bundle:
    runs-on: ubuntu-latest

    needs: build_android

    steps:
      - name: Download Android App Bundle
        run: |
          mkdir -p $GITHUB_WORKSPACE/dist
          cp $GITHUB_WORKSPACE/android/app/build/outputs/bundle/release/app-release.aab $GITHUB_WORKSPACE/dist
        working-directory: telon-gateway-app


      - name: Archive Bundle
        uses: actions/upload-artifact@v2
        with:
          name: android-bundle
          path: $GITHUB_WORKSPACE/dist
